# Generated by Django 5.1.3 on 2024-11-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Depósito"),
                            ("EXPENSE", "Despesa"),
                            ("INVESTMENT", "Investimento"),
                        ],
                        max_length=25,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Valor"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HOUSING", "Moradia"),
                            ("TRANSPORTATION", "Transporte"),
                            ("FOOD", "Alimentação"),
                            ("ENTERTAINMENT", "Entretenimento"),
                            ("HEALTH", "Saúde"),
                            ("UTILITY", "Utilidades"),
                            ("SALARY", "Salário"),
                            ("EDUCATION", "Educação"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=25,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "paymentMethod",
                    models.CharField(
                        choices=[
                            ("CREDIT_CARD", "Cartão de Crédito"),
                            ("DEBIT_CARD", "Cartão de Débito"),
                            ("BANK_TRANSFER", "Transferência Bancária"),
                            ("BANK_SLIP", "Boleto Bancário"),
                            ("CASH", "Dinheiro"),
                            ("PIX", "PIX"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=25,
                        verbose_name="Método de Pagamento",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "createdAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Transação",
                "verbose_name_plural": "Transações",
                "ordering": ["-updatedAt"],
            },
        ),
    ]
